### ISSUE TITLE
Error on execution

### ISSUE THREAD

**Issue by darkikari** [Azure-Samples/iot-hub-node-raspberrypi-client-app#7]
A error occurs when try to simulate the device.

> sudo node index.js '<my string>'
> 
> Unable to determine hardware version. I see: Hardware   : BCM2835
> 
>  - expecting BCM2708 or BCM2709. Please report this to projects@drogon.net

All the configuration was done info the config.json but dosn't work, how?

My config file : 
>   "simulatedData": true,
>   "interval": 2000,
>   "deviceId": "Raspberry Pi Node",
>   "LEDPin": 7,
>   "messageMax": 256,
>   "credentialPath": "~/.iot-hub",
>   "temperatureAlert": 30,
>   "i2cOption": {
>     "pin": 9,
>     "i2cBusNo": 1,
>     "i2cAddress": 119

**Comment by yuwzho** [comment]
Hi @darkikari , it seems to be related to the new Kernel Version 4.9. You can see the same issue at: https://github.com/WiringPi/WiringPi-Node/issues/70 .

As this issue metions, for a quick workround, you can install [wiringpi-node](https://www.npmjs.com/package/wiringpi-node) instead of `wiring-pi`.
And then, in the [`index.js`](https://github.com/Azure-Samples/iot-hub-node-raspberrypi-client-app/blob/05ea7e668dc9bca5eaa944c045ec9a8c1c538d31/index.js#L10), use `require('wiringpi-node')` to solve your problem.

**Comment by darkikari** [comment]
Hi, thanks for your answer @yuwzho, I could execute correctly :)

**Comment by salmanfarisvp** [comment]
i also facing the same issue and  i just added the` require('wiringpi-node')` in the `index.js` file , 
after that getting same error :- 
```
Unable to determine hardware version. I see: Hardware   : BCM2835
,
 - expecting BCM2708 or BCM2709. Please report this to projects@drogon.net
```
